sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        uwYUgUPLDhSyYJxOwvpYT81BKF0hw0ErjXsX8/x+8CuXkjvv9ZWgns9HJn9wSIq6knkSvELAjcV+mpVwe+cxOgB/DlGpR0IOsFkZzJovPV+dqanOySFIJox4/1srObnje/Uws3oDw6mIwMyozO8DbdfT6mEEeQ81Yje1Ws/q64rQ6cpKPYy3Xf6tUf7kVQGmFNWiWpd9UGFi1YZimc9MeKC+s1l5D2hGAOgJYw2FNwldNk5V7DWEGaHUktw7amzX7X4EbEg72507aAT/iS1LPpXB588d82KkPxLaxKt0aysws86QFrEdpU5Wa2dAcMm0SiEAaCyuCBwbAzYl3eD+Qsc34r7Y3RQ8pvPMrQViNTTSq4n/T1Y7dqTxmuDxwIc228VIgqmldpBbxtuk+PAp8GXokyScU9WBFWS7i1E/8aBkNYXMYYIk9zsevTbqBvfF5ZXrm0DFtXC9teKq3e8pqdLskyEaFxbvMr5bNJWjQVJFz9wfu2Kk1KDBX1uX6XkTKy+raZi6cFiqLxPdvk9FyLTMgPZ5cGIVtjzM+i9qdBUJvV8tEyZ13gPx1USsnWt4GeZPQUg+i/dOhKnu+TD1SIJUMoL/JICEhWZD+oF7bp9n0+0syGxu1mb9w+ApszrQyBr2ZCultPHDnl1xXToNPEEnNyQ8PXlAVZ36puJG90M=
    - secure: >-
        3sfytvuwWH9n/qT2gsUNRBU66FrI8Ul1ZnEsNfzJoGHFt8mZduIPIM/yPrm7rbXVlr//mvACVNVPqwowWs4ydlF6o6ZwNU16g1ppwvPP5pogGvxF0Fy8qy6BNReqTz0gHyuVldanwrT7WWz1lcKJr0SdLbV/V+kg63j0io+UE9RsJsNLQI0WIxHfsyO+luW2yReU/F6MU4wcyWfd8ri5qZLwo8LZ/9A2UlU4jsFe4kPXAB6P1H5SIzHVXb8xVi3ZMEH0lqejiN3Lu4G0IKTKoj68v/iIFoWAwzQfDg+T65lnI/SjmxgYJOoJldIEUVeosBRC/F8NmC/bX9tPMWus4rOGTO/b6d25aOsFrBnZw7XooejHm2tGEmz3Ca1NGITNrkDAXST6Cyf0lUKRtmErgwtZpc8ueSXYNZJOSn58PSckTaVLe1JHfH3r1hB9jBLZXG+7YeoLYj1cVhVenWDusxu85NWmNLhFQuJDKqyWkATs7Gn843pwECK8EOrOXpBn8rdz3NOUwehXuhpbVdhBfznI/TowU4ua9FaKeHfZBxZ50f6x1AwEjiKgKIuz5fAHjnWb0OVSKC0kT52JL7wq4weVZ/9eE6nLo3f1FxGBZ2uAN20vCzlFX3RpBf2uqpgEbOsglxq66XY9X3fGxj9VX3SLc2can/cQIZp6u2WbDxg=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
